export const generatedAdminErrors = {
  "zh-TW": {
    "UNAUTHORIZED": "您的會話已過期。請重新登入。",
    "INVALID_CREDENTIALS": "管理員密碼不正確。",
    "LOGIN_RATE_LIMITED": "登入嘗試次數過多。請稍後再試。",
    "PASSWORD_LENGTH": "密碼長度必須為 10 到 512 個字元。",
    "PASSWORD_CONFIRM_MISMATCH": "兩次輸入的密碼不匹配。",
    "FRONTEND_PASSWORD_REQUIRED": "在啟用此選項前，請設定前端密碼。",
    "TOKEN_NAME_REQUIRED": "請輸入一個令牌名稱。",
    "INVALID_TOKEN_RATE_LIMIT": "令牌速率限制無效。",
    "INVALID_TOKEN_VALUE": "令牌值的長度或格式無效。",
    "INVALID_TOKEN_SCOPES": "令牌範圍無效。",
    "INVALID_TOKEN_EXPIRY": "令牌過期時間無效。",
    "TOKEN_ALREADY_EXISTS": "該令牌值已存在。",
    "API_TOKEN_NOT_FOUND": "未找到此令牌。",
    "API_TOKEN_SECRET_UNAVAILABLE": "此令牌僅保留身份驗證資料。",
    "NO_AVAILABLE_KEY": "至少添加一個啟用且未過期的憑證。",
    "PROVIDER_TEST_FAILED": "憑證測試失敗。",
    "INVALID_USER_KEY": "服務憑證無效。",
    "CHINA_SYNC_BUSY": "中國同步任務已在運行。",
    "CREDENTIAL_NOT_FOUND": "未找到服務憑證。",
    "INVALID_PROVIDER_CREDENTIAL": "憑證配置無效。",
    "INVALID_MAP_DISPLAY_CONFIG": "地圖顯示配置無效。",
    "INVALID_BROWSER_MAP_CREDENTIAL": "高德地圖 Web 憑證無效。",
    "BROWSER_MAP_CREDENTIAL_EXISTS": "高德地圖 Web 憑證已存在。",
    "BROWSER_MAP_CREDENTIAL_NOT_FOUND": "未找到高德地圖 Web 憑證。",
    "AREACITY_DATA_EMPTY": "AreaCity 資料是空的。",
    "INVALID_AREACITY_CSV": "AreaCity CSV 格式無效。",
    "AREACITY_SOURCE_OUTSIDE_DATA_ROOT": "AreaCity 檔案必須在本地資料目錄內。"
  },
  "ja": {
    "UNAUTHORIZED": "セッションの有効期限が切れました。再度サインインしてください。",
    "INVALID_CREDENTIALS": "管理者パスワードが正しくありません。",
    "LOGIN_RATE_LIMITED": "サインイン試行回数が多すぎます。後でもう一度試してください。",
    "PASSWORD_LENGTH": "パスワードの長さは10文字から512文字である必要があります。",
    "PASSWORD_CONFIRM_MISMATCH": "2回のパスワード入力が一致しません。",
    "FRONTEND_PASSWORD_REQUIRED": "このオプションを有効にする前にフロントエンドのパスワードを設定してください。",
    "TOKEN_NAME_REQUIRED": "トークン名を入力してください。",
    "INVALID_TOKEN_RATE_LIMIT": "トークンのレート制限が無効です。",
    "INVALID_TOKEN_VALUE": "トークンの値の長さまたは形式が無効です。",
    "INVALID_TOKEN_SCOPES": "トークンのスコープが無効です。",
    "INVALID_TOKEN_EXPIRY": "トークンの有効期限が無効です。",
    "TOKEN_ALREADY_EXISTS": "そのトークンの値は既に存在します。",
    "API_TOKEN_NOT_FOUND": "トークンが見つかりませんでした。",
    "API_TOKEN_SECRET_UNAVAILABLE": "このトークンは認証データのみを保持します。",
    "NO_AVAILABLE_KEY": "少なくとも1つの有効で期限切れでない資格情報を追加してください。",
    "PROVIDER_TEST_FAILED": "資格情報のテストに失敗しました。",
    "INVALID_USER_KEY": "サービスの認証情報が無効です。",
    "CHINA_SYNC_BUSY": "中国同期タスクがすでに実行中です。",
    "CREDENTIAL_NOT_FOUND": "サービスの認証情報が見つかりませんでした。",
    "INVALID_PROVIDER_CREDENTIAL": "認証情報の設定が無効です。",
    "INVALID_MAP_DISPLAY_CONFIG": "マップ表示の設定が無効です。",
    "INVALID_BROWSER_MAP_CREDENTIAL": "AMap Web の認証情報が無効です。",
    "BROWSER_MAP_CREDENTIAL_EXISTS": "AMap Web の認証情報はすでに存在します。",
    "BROWSER_MAP_CREDENTIAL_NOT_FOUND": "AMap Web の認証情報が見つかりませんでした。",
    "AREACITY_DATA_EMPTY": "AreaCity のデータは空です。",
    "INVALID_AREACITY_CSV": "AreaCity の CSV 形式が無効です。",
    "AREACITY_SOURCE_OUTSIDE_DATA_ROOT": "AreaCity ファイルはローカルのデータディレクトリ内に存在する必要があります。"
  },
  "ko": {
    "UNAUTHORIZED": "세션이 만료되었습니다. 다시 로그인하세요.",
    "INVALID_CREDENTIALS": "관리자 비밀번호가 올바르지 않습니다.",
    "LOGIN_RATE_LIMITED": "로그인 시도가 너무 많습니다. 나중에 다시 시도하세요.",
    "PASSWORD_LENGTH": "비밀번호 길이는 10자에서 512자여야 합니다.",
    "PASSWORD_CONFIRM_MISMATCH": "두 비밀번호 입력이 일치하지 않습니다.",
    "FRONTEND_PASSWORD_REQUIRED": "이 옵션을 활성화하기 전에 프론트엔드 비밀번호를 설정하세요.",
    "TOKEN_NAME_REQUIRED": "토큰 이름을 입력하세요.",
    "INVALID_TOKEN_RATE_LIMIT": "토큰 속도 제한이 올바르지 않습니다.",
    "INVALID_TOKEN_VALUE": "토큰 값의 길이나 형식이 잘못되었습니다.",
    "INVALID_TOKEN_SCOPES": "토큰 범위가 잘못되었습니다.",
    "INVALID_TOKEN_EXPIRY": "토큰 만료가 잘못되었습니다.",
    "TOKEN_ALREADY_EXISTS": "해당 토큰 값이 이미 존재합니다.",
    "API_TOKEN_NOT_FOUND": "토큰을 찾을 수 없습니다.",
    "API_TOKEN_SECRET_UNAVAILABLE": "이 토큰은 인증 데이터만 보관합니다.",
    "NO_AVAILABLE_KEY": "하나 이상의 활성화된 만료되지 않은 자격 증명을 추가하세요.",
    "PROVIDER_TEST_FAILED": "자격 증명 테스트에 실패했습니다.",
    "INVALID_USER_KEY": "서비스 자격 증명이 유효하지 않습니다.",
    "CHINA_SYNC_BUSY": "중국 동기화 작업이 이미 실행 중입니다.",
    "CREDENTIAL_NOT_FOUND": "서비스 자격 증명을 찾을 수 없습니다.",
    "INVALID_PROVIDER_CREDENTIAL": "자격 증명 구성이 유효하지 않습니다.",
    "INVALID_MAP_DISPLAY_CONFIG": "지도 표시 구성이 유효하지 않습니다.",
    "INVALID_BROWSER_MAP_CREDENTIAL": "AMap 웹 자격 증명이 유효하지 않습니다.",
    "BROWSER_MAP_CREDENTIAL_EXISTS": "AMap 웹 자격 증명이 이미 존재합니다.",
    "BROWSER_MAP_CREDENTIAL_NOT_FOUND": "AMap 웹 자격 증명을 찾을 수 없습니다.",
    "AREACITY_DATA_EMPTY": "AreaCity 데이터가 비어 있습니다.",
    "INVALID_AREACITY_CSV": "AreaCity CSV 형식이 유효하지 않습니다.",
    "AREACITY_SOURCE_OUTSIDE_DATA_ROOT": "AreaCity 파일은 로컬 데이터 디렉터리 안에 있어야 합니다."
  },
  "de": {
    "UNAUTHORIZED": "Ihre Sitzung ist abgelaufen. Melden Sie sich erneut an.",
    "INVALID_CREDENTIALS": "Das Administratorpasswort ist falsch.",
    "LOGIN_RATE_LIMITED": "Zu viele Anmeldeversuche. Versuchen Sie es später erneut.",
    "PASSWORD_LENGTH": "Die Passwortlänge muss 10 bis 512 Zeichen betragen.",
    "PASSWORD_CONFIRM_MISMATCH": "Die beiden Passworteingaben stimmen nicht überein.",
    "FRONTEND_PASSWORD_REQUIRED": "Legen Sie ein Frontend-Passwort fest, bevor Sie diese Option aktivieren.",
    "TOKEN_NAME_REQUIRED": "Geben Sie einen Token-Namen ein.",
    "INVALID_TOKEN_RATE_LIMIT": "Das Token-Ratenlimit ist ungültig.",
    "INVALID_TOKEN_VALUE": "Der Tokenwert hat eine ungültige Länge oder ein ungültiges Format.",
    "INVALID_TOKEN_SCOPES": "Die Token-Bereiche sind ungültig.",
    "INVALID_TOKEN_EXPIRY": "Das Token-Ablaufdatum ist ungültig.",
    "TOKEN_ALREADY_EXISTS": "Dieser Tokenwert existiert bereits.",
    "API_TOKEN_NOT_FOUND": "Der Token wurde nicht gefunden.",
    "API_TOKEN_SECRET_UNAVAILABLE": "Dieser Token speichert nur Authentifizierungsdaten.",
    "NO_AVAILABLE_KEY": "Fügen Sie mindestens eine aktivierte, nicht abgelaufene Anmeldeinformation hinzu.",
    "PROVIDER_TEST_FAILED": "Der Anmeldeinformationstest ist fehlgeschlagen.",
    "INVALID_USER_KEY": "Die Dienstanmeldeinformationen sind ungültig.",
    "CHINA_SYNC_BUSY": "Eine China-Synchronisierungsaufgabe läuft bereits.",
    "CREDENTIAL_NOT_FOUND": "Die Dienstanmeldeinformationen wurden nicht gefunden.",
    "INVALID_PROVIDER_CREDENTIAL": "Die Anmeldeinformationskonfiguration ist ungültig.",
    "INVALID_MAP_DISPLAY_CONFIG": "Die Kartenanzeigekonfiguration ist ungültig.",
    "INVALID_BROWSER_MAP_CREDENTIAL": "Die AMap-Webanmeldeinformationen sind ungültig.",
    "BROWSER_MAP_CREDENTIAL_EXISTS": "Es existieren bereits AMap-Webanmeldeinformationen.",
    "BROWSER_MAP_CREDENTIAL_NOT_FOUND": "Die AMap-Webanmeldeinformationen wurden nicht gefunden.",
    "AREACITY_DATA_EMPTY": "Die AreaCity-Daten sind leer.",
    "INVALID_AREACITY_CSV": "Das AreaCity-CSV-Format ist ungültig.",
    "AREACITY_SOURCE_OUTSIDE_DATA_ROOT": "Die AreaCity-Datei muss sich im lokalen Datenverzeichnis befinden."
  },
  "fr": {
    "UNAUTHORIZED": "Votre session a expiré. Connectez-vous à nouveau.",
    "INVALID_CREDENTIALS": "Le mot de passe administrateur est incorrect.",
    "LOGIN_RATE_LIMITED": "Trop de tentatives de connexion. Réessayez plus tard.",
    "PASSWORD_LENGTH": "La longueur du mot de passe doit être comprise entre 10 et 512 caractères.",
    "PASSWORD_CONFIRM_MISMATCH": "Les deux saisies du mot de passe ne correspondent pas.",
    "FRONTEND_PASSWORD_REQUIRED": "Définissez un mot de passe pour l'interface avant d'activer cette option.",
    "TOKEN_NAME_REQUIRED": "Entrez un nom de jeton.",
    "INVALID_TOKEN_RATE_LIMIT": "La limite de taux du jeton est invalide.",
    "INVALID_TOKEN_VALUE": "La valeur du jeton a une longueur ou un format invalide.",
    "INVALID_TOKEN_SCOPES": "Les portées du jeton sont invalides.",
    "INVALID_TOKEN_EXPIRY": "La date d'expiration du jeton est invalide.",
    "TOKEN_ALREADY_EXISTS": "Cette valeur de jeton existe déjà.",
    "API_TOKEN_NOT_FOUND": "Le jeton est introuvable.",
    "API_TOKEN_SECRET_UNAVAILABLE": "Ce jeton ne contient que des données d'authentification.",
    "NO_AVAILABLE_KEY": "Ajoutez au moins un identifiant activé et non expiré.",
    "PROVIDER_TEST_FAILED": "Le test de l'identifiant a échoué.",
    "INVALID_USER_KEY": "Les informations d'identification du service sont invalides.",
    "CHINA_SYNC_BUSY": "Une tâche de synchronisation en Chine est déjà en cours.",
    "CREDENTIAL_NOT_FOUND": "Les informations d'identification du service n'ont pas été trouvées.",
    "INVALID_PROVIDER_CREDENTIAL": "La configuration des informations d'identification est invalide.",
    "INVALID_MAP_DISPLAY_CONFIG": "La configuration de l'affichage de la carte est invalide.",
    "INVALID_BROWSER_MAP_CREDENTIAL": "Les informations d'identification AMap Web sont invalides.",
    "BROWSER_MAP_CREDENTIAL_EXISTS": "Une information d'identification AMap Web existe déjà.",
    "BROWSER_MAP_CREDENTIAL_NOT_FOUND": "Les informations d'identification AMap Web n'ont pas été trouvées.",
    "AREACITY_DATA_EMPTY": "Les données d'AreaCity sont vides.",
    "INVALID_AREACITY_CSV": "Le format CSV d'AreaCity est invalide.",
    "AREACITY_SOURCE_OUTSIDE_DATA_ROOT": "Le fichier AreaCity doit se trouver dans le répertoire de données local."
  },
  "es": {
    "UNAUTHORIZED": "Tu sesión ha caducado. Inicia sesión de nuevo.",
    "INVALID_CREDENTIALS": "La contraseña del administrador es incorrecta.",
    "LOGIN_RATE_LIMITED": "Demasiados intentos de inicio de sesión. Inténtalo de nuevo más tarde.",
    "PASSWORD_LENGTH": "La longitud de la contraseña debe ser de 10 a 512 caracteres.",
    "PASSWORD_CONFIRM_MISMATCH": "Las dos entradas de la contraseña no coinciden.",
    "FRONTEND_PASSWORD_REQUIRED": "Establece una contraseña de frontend antes de habilitar esta opción.",
    "TOKEN_NAME_REQUIRED": "Ingresa un nombre para el token.",
    "INVALID_TOKEN_RATE_LIMIT": "El límite de velocidad del token no es válido.",
    "INVALID_TOKEN_VALUE": "El valor del token tiene una longitud o formato inválido.",
    "INVALID_TOKEN_SCOPES": "Los alcances del token son inválidos.",
    "INVALID_TOKEN_EXPIRY": "La expiración del token es inválida.",
    "TOKEN_ALREADY_EXISTS": "Ese valor de token ya existe.",
    "API_TOKEN_NOT_FOUND": "No se encontró el token.",
    "API_TOKEN_SECRET_UNAVAILABLE": "Este token solo conserva datos de autenticación.",
    "NO_AVAILABLE_KEY": "Agrega al menos una credencial habilitada y no expirada.",
    "PROVIDER_TEST_FAILED": "La prueba de la credencial falló.",
    "INVALID_USER_KEY": "La credencial del servicio no es válida.",
    "CHINA_SYNC_BUSY": "Ya se está ejecutando una tarea de sincronización de China.",
    "CREDENTIAL_NOT_FOUND": "No se encontró la credencial del servicio.",
    "INVALID_PROVIDER_CREDENTIAL": "La configuración de la credencial no es válida.",
    "INVALID_MAP_DISPLAY_CONFIG": "La configuración de visualización del mapa no es válida.",
    "INVALID_BROWSER_MAP_CREDENTIAL": "La credencial de AMap Web no es válida.",
    "BROWSER_MAP_CREDENTIAL_EXISTS": "Ya existe una credencial de AMap Web.",
    "BROWSER_MAP_CREDENTIAL_NOT_FOUND": "No se encontró la credencial de AMap Web.",
    "AREACITY_DATA_EMPTY": "Los datos de AreaCity están vacíos.",
    "INVALID_AREACITY_CSV": "El formato CSV de AreaCity no es válido.",
    "AREACITY_SOURCE_OUTSIDE_DATA_ROOT": "El archivo de AreaCity debe estar dentro del directorio de datos local."
  },
  "pt": {
    "UNAUTHORIZED": "Sua sessão expirou. Faça login novamente.",
    "INVALID_CREDENTIALS": "A senha do administrador está incorreta.",
    "LOGIN_RATE_LIMITED": "Muitas tentativas de login. Tente novamente mais tarde.",
    "PASSWORD_LENGTH": "O comprimento da senha deve ter entre 10 e 512 caracteres.",
    "PASSWORD_CONFIRM_MISMATCH": "As duas entradas de senha não correspondem.",
    "FRONTEND_PASSWORD_REQUIRED": "Defina uma senha de frontend antes de ativar esta opção.",
    "TOKEN_NAME_REQUIRED": "Digite um nome para o token.",
    "INVALID_TOKEN_RATE_LIMIT": "O limite de taxa do token é inválido.",
    "INVALID_TOKEN_VALUE": "O valor do token possui um comprimento ou formato inválido.",
    "INVALID_TOKEN_SCOPES": "Os escopos do token são inválidos.",
    "INVALID_TOKEN_EXPIRY": "A expiração do token é inválida.",
    "TOKEN_ALREADY_EXISTS": "Esse valor de token já existe.",
    "API_TOKEN_NOT_FOUND": "O token não foi encontrado.",
    "API_TOKEN_SECRET_UNAVAILABLE": "Este token retém apenas dados de autenticação.",
    "NO_AVAILABLE_KEY": "Adicione pelo menos uma credencial habilitada e que não tenha expirado.",
    "PROVIDER_TEST_FAILED": "O teste da credencial falhou.",
    "INVALID_USER_KEY": "A credencial de serviço é inválida.",
    "CHINA_SYNC_BUSY": "Uma tarefa de sincronização com a China já está em execução.",
    "CREDENTIAL_NOT_FOUND": "A credencial de serviço não foi encontrada.",
    "INVALID_PROVIDER_CREDENTIAL": "A configuração da credencial é inválida.",
    "INVALID_MAP_DISPLAY_CONFIG": "A configuração de exibição do mapa é inválida.",
    "INVALID_BROWSER_MAP_CREDENTIAL": "A credencial AMap Web é inválida.",
    "BROWSER_MAP_CREDENTIAL_EXISTS": "Uma credencial AMap Web já existe.",
    "BROWSER_MAP_CREDENTIAL_NOT_FOUND": "A credencial AMap Web não foi encontrada.",
    "AREACITY_DATA_EMPTY": "Os dados de AreaCity estão vazios.",
    "INVALID_AREACITY_CSV": "O formato CSV de AreaCity é inválido.",
    "AREACITY_SOURCE_OUTSIDE_DATA_ROOT": "O arquivo AreaCity deve estar dentro do diretório de dados local."
  }
};
