import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

const workflow = await readFile(new URL('../.github/workflows/address-lite.yml', import.meta.url), 'utf8');
describe('Address Lite workflow architecture', () => {
  it('keeps source refresh as one native sequential job', () => { const source = workflow.slice(workflow.indexOf('  source-refresh:'), workflow.indexOf('  data-assemble:')); expect(source).toContain('build-native.mjs'); expect(source).not.toContain('strategy:'); expect(source).not.toContain('matrix:'); expect(source).not.toContain('npm ci'); expect(source).not.toContain('cache: npm'); expect(workflow).not.toContain('POSTGRES_URL'); expect(workflow).not.toContain('setup-python'); });
  it('prepares a verified selected Snapshot fallback before native refresh', () => { const source = workflow.slice(workflow.indexOf('  source-refresh:'), workflow.indexOf('  data-assemble:')); expect(source).toContain('address-lite-selected-data'); expect(source).toContain('address-lite-data.tar.gz'); expect(source).toContain('verify-static.mjs --data'); expect(source).toContain('--fallback-data'); });
  it('does not route active Lite workflow through server/database or server/sync', () => { const active = workflow.slice(workflow.indexOf('jobs:')); expect(active).not.toMatch(/server\/(database|sync)/); });
  it('checks protected Production anonymously without weakening TLS', () => { const smoke = workflow.slice(workflow.indexOf('      - name: Public HTTPS smoke test')); const credentialNames = new RegExp(`${['BASIC', 'AUTH'].join('_')}_|${['HTTP', 'AUTH'].join('_')}_`); const tlsBypass = ['curl -', 'k'].join(''); const insecureFlag = ['--', 'insecure'].join(''); expect(workflow).toContain('https://address.zhuzhu.jiejie12131.top'); expect(smoke).toContain("status=\"$(curl -sS"); expect(smoke).toContain("== '401'"); expect(smoke).toContain('WWW-Authenticate'); expect(smoke).not.toContain(tlsBypass); expect(smoke).not.toContain(insecureFlag); expect(smoke).not.toMatch(credentialNames); });
});
