import { mkdtemp, readFile, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { ENDPOINTS, MAX_HTTP_REQUESTS, REFERER, USER_AGENT, createOverpassClient, filterAddresses, overpassQuery, probeWindows, runNativeRefresh } from '../scripts/lite/build-native.mjs';

const target = (scope, bounds = [-10, -10, 10, 10]) => ({ id: 'T', label: 'Test', scope, bounds, seeds: [[0, 0], [1, 1], [2, 2], [3, 3], [4, 4]] });
const building = (building = 'house', tags = {}) => ({ type: 'way', id: Math.random(), center: { lon: 0, lat: 0 }, tags: { building, 'addr:housenumber': '1', 'addr:street': 'Main', ...tags } });
const response = (status = 200, data = { elements: [] }, headers = {}) => ({ ok: status >= 200 && status < 300, status, headers: { get: key => headers[key.toLowerCase()] || null }, json: async () => data });
const tinyManifest = (file = 'US/T.json') => ({ targets: [{ ...target('city'), country: 'US', file }], candidateProfiles: { city: { outputCap: 5 } } });
const baselineShard = fileTarget => ({ schemaVersion: 1, country: 'US', target: { id: 'T' }, stats: { addresses: 1 }, regions: [{ name: 'Test', cities: [{ name: 'Test', postcodes: [{ postcode: '1', addresses: [{ id: 'old', propertyType: 'residential', residentialEvidence: true, street: 'Main', houseNumber: '1', latitude: 0, longitude: 0, source: { name: 'OpenStreetMap', attribution: '© OpenStreetMap contributors' } }] }] }] }], fileTarget });

describe('Address Lite native bounded Overpass refresh', () => {
  it.each([['micro', .01, .01], ['city', .02, .015], ['region', .035, .025]])('uses %s radius', (scope, dx, dy) => { const box = probeWindows(target(scope), 1)[0]; expect(box).toEqual([-dx, -dy, dx, dy]); });
  it('doubles pass 2 radius and emits south,west,north,east', () => { expect(probeWindows(target('micro'), 2)[0]).toEqual([-.02, -.02, .02, .02]); expect(overpassQuery([[1, 2, 3, 4]])).toContain('(2,1,4,3)'); expect(overpassQuery([[1, 2, 3, 4]])).not.toContain('around:'); });
  it('strictly accepts residential and rejects commercial/amenity/outside records', () => { expect(filterAddresses([building()], target('micro'))).toHaveLength(1); expect(filterAddresses([building('commercial'), building('house', { shop: 'yes' }), building('house', { office: 'yes' }), building('house', { amenity: 'school' }), { ...building(), center: { lon: 99, lat: 99 } }], target('micro'))).toHaveLength(0); });
  it('declares the required endpoint pool and request headers', async () => { expect(ENDPOINTS).toEqual(['https://overpass.private.coffee/api/interpreter', 'https://maps.mail.ru/osm/tools/overpass/api/interpreter', 'https://overpass-api.de/api/interpreter']); expect(ENDPOINTS.join(' ')).not.toContain('kumi.systems'); const calls = []; const client = createOverpassClient({ fetchImpl: async (url, options) => { calls.push([url, options]); return response(); } }); await client.healthProbe(); await client.request(overpassQuery([])); expect(calls[0][1].headers).toMatchObject({ 'User-Agent': USER_AGENT, Referer: REFERER, Accept: 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' }); });
  it('health probe continues with one healthy endpoint and fails when all fail', async () => { const healthy = createOverpassClient({ fetchImpl: async url => url.includes('mail.ru') ? response() : response(500) }); await expect(healthy.healthProbe()).resolves.toBeUndefined(); expect(healthy.metrics.healthyEndpoints).toHaveLength(1); const dead = createOverpassClient({ fetchImpl: async () => response(500) }); await expect(dead.healthProbe()).rejects.toThrow('overpass_no_healthy_endpoint'); });
  it('fails over on 500 and applies 429 cooldown', async () => { const seen = []; const client = createOverpassClient({ fetchImpl: async (url, options) => { seen.push([url, options]); if (seen.length <= 3) return response(); if (url.includes('private.coffee')) return response(500); return response(200, { elements: [] }); } }); await client.healthProbe(); await client.request(overpassQuery([])); expect(client.metrics.healthyEndpoints.length).toBe(3); const failing = createOverpassClient({ fetchImpl: async (url) => { if (url.includes('private.coffee')) return response(429, {}, { 'retry-after': '30' }); return response(); } }); await failing.healthProbe(); await failing.request(overpassQuery([])); expect(failing.metrics.endpoint429['overpass.private.coffee']).toBe(1); });
  it('exposes the global request budget', () => expect(MAX_HTTP_REQUESTS).toBe(90));
  it('supports three postcode slots per group and output caps', () => { const records = [1, 2, 3, 4].map(id => ({ ...building(), id, tags: { ...building().tags, 'addr:postcode': '1000' } })); expect(new Set(records.map(record => record.tags['addr:postcode'])).size).toBe(1); expect(records).toHaveLength(4); });
  it('reuses a verified baseline on network failure without failing refresh', async () => { const base = await mkdtemp(join(tmpdir(), 'lite-baseline-')); const out = await mkdtemp(join(tmpdir(), 'lite-out-')); await mkdir(join(base, 'US'), { recursive: true }); await writeFile(join(base, 'US/T.json'), `${JSON.stringify(baselineShard('US/T.json'))}\n`); let calls = 0; const metrics = await runNativeRefresh({ manifest: tinyManifest(), seeds: { targets: { T: [[0, 0]] } }, out, fallbackData: base, metricsFile: join(out, 'metrics.json'), fetchImpl: async () => { calls += 1; if (calls <= 3) return response(); throw new Error('fetch failed'); }, log: () => {} }); expect(metrics.refreshedTargets).toBe(0); expect(metrics.reusedNetworkTargets).toBe(1); expect(metrics.fatalTargets).toHaveLength(0); expect(JSON.parse(await readFile(join(out, 'US/T.json'))).stats.addresses).toBe(1); });
  it('marks a target fatal when no baseline exists and refresh fails', async () => { const out = await mkdtemp(join(tmpdir(), 'lite-out-')); let calls = 0; await expect(runNativeRefresh({ manifest: tinyManifest(), seeds: { targets: { T: [[0, 0]] } }, out, metricsFile: join(out, 'metrics.json'), fallbackData: join(out, 'missing'), fetchImpl: async () => { calls += 1; if (calls <= 3) return response(); throw new Error('fetch failed'); }, log: () => {} })).rejects.toThrow('T'); });
});
