import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import process from 'node:process';

const root = resolve(new URL('../..', import.meta.url).pathname);
const manifest = JSON.parse(await readFile(resolve(root, 'config/lite-targets.json'), 'utf8'));
const seeds = JSON.parse(await readFile(resolve(root, 'config/lite-seeds.json'), 'utf8'));
const arg = (name, fallback = '') => { const i = process.argv.indexOf(name); return i >= 0 ? process.argv[i + 1] : fallback; };
const out = resolve(arg('--out', resolve(root, '.lite-output')));
const metricsPath = resolve(arg('--metrics', resolve(out, 'metrics/native.json')));
const residential = new Set(['apartments','bungalow','cabin','detached','dormitory','ger','house','residential','semidetached_house','semi','terrace']);
const blocked = ['amenity','shop','office','tourism','industrial','craft','healthcare','military'];
const norm = v => String(v || '').normalize('NFKD').replace(/\p{M}+/gu, '').trim().toLocaleLowerCase('und');
const inside = (x, y, b) => x >= b[0] && x <= b[2] && y >= b[1] && y <= b[3];
const windows = (t, radius) => (seeds.targets[t.id] || []).map(([x,y]) => [Math.max(t.bounds[0],x-radius[0]),Math.max(t.bounds[1],y-radius[1]),Math.min(t.bounds[2],x+radius[0]),Math.min(t.bounds[3],y+radius[1])]);
const query = boxes => `[out:json][timeout:45];( ${boxes.map(b => `nwr[building~"^(apartments|bungalow|cabin|detached|dormitory|ger|house|residential|semidetached_house|semi|terrace)$"]["addr:housenumber"](around:1,${(b[1]+b[3])/2},${(b[0]+b[2])/2});`).join(' ')} );out center tags;`;
async function overpass(body) {
  let last;
  for (let i=0;i<3;i++) for (const endpoint of ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter']) {
    try { const r=await fetch(endpoint,{method:'POST',body:new URLSearchParams({data:body}),signal:AbortSignal.timeout(50000)}); if(r.ok)return r.json(); if(![408,429,500,502,503,504].includes(r.status)) throw new Error(`Overpass HTTP ${r.status}`); last=new Error(`Overpass HTTP ${r.status}`); } catch(e){last=e;}
    if(endpoint.includes('kumi')) await new Promise(r=>setTimeout(r,(i+1)*1000));
  }
  throw last;
}
const makeAddress = (e,t) => { const g=e.center || (e.lat && e.lon ? {lat:e.lat,lon:e.lon}:null), q=e.tags||{}; if(!g||!residential.has(q.building)||!q['addr:housenumber']||!(q['addr:street']||q['addr:place'])||blocked.some(k=>q[k]&& !['','no','none'].includes(norm(q[k]))))return null; if(!inside(g.lon,g.lat,t.bounds))return null; const region=q['addr:state']||q['addr:province']||q['addr:region']||t.label; if(t.regionAliases?.length&&(q['addr:state']||q['addr:province']||q['addr:region'])&&!t.regionAliases.some(a=>norm(a)===norm(region)))return null; const city=q['addr:city']||q['addr:town']||q['addr:municipality']||q['addr:village']||q['addr:suburb']||t.label; const street=q['addr:street']||q['addr:place']; const postcode=q['addr:postcode']||''; const score=100+(postcode?20:0)+(city?10:0)+((q['addr:state']||q['addr:province'])?5:0)+(q.building==='apartments'?2:0); const type=e.type; const id=`osm:${type}:${e.id}`; return {id,region,regionCode:q['addr:state_code']||'',city,locality:city,postalLocality:city,district:q['addr:district']||q['addr:county']||q['addr:suburb']||'',postcode,street,houseNumber:q['addr:housenumber'],buildingName:q.name||'',unit:q['addr:unit']||q['addr:flats']||'',latitude:g.lat,longitude:g.lon,propertyType:q.building==='apartments'?'apartment':'residential',residentialEvidence:true,qualityScore:score,formattedAddress:[q['addr:housenumber'],street,city,region,postcode,q['addr:country']].filter(Boolean).join(', '),formattedAddressEn:'',formattedAddressZh:'',source:{name:'OpenStreetMap',url:`https://www.openstreetmap.org/${type}/${e.id}`,license:'ODbL 1.0',licenseUrl:'https://opendatacommons.org/licenses/odbl/1-0/',attribution:'© OpenStreetMap contributors',attributionUrl:'https://www.openstreetmap.org/copyright',datasetVersion:`overpass:${new Date().toISOString().slice(0,10)}`,sourceRecordId:`${type}/${e.id}`}};
};
const started=Date.now(), stats={startedAt:new Date(started).toISOString(),countries:0,targets:manifest.targets.length,requests:0,retries:0,fallbackRequests:0,elementsReceived:0,acceptedAddresses:0,emptyTargets:0,failedCountries:[]};
await mkdir(out,{recursive:true});
for(const country of [...new Set(manifest.targets.map(t=>t.country))]){const ts=manifest.targets.filter(t=>t.country===country);try{const all=new Map();for(const radius of [[.01,.01,.01,.01],[.02,.015,.02,.015]]){const pending=ts.filter(t=>!all.has(t.id)||all.get(t.id).length<3);if(!pending.length)break;const boxes=pending.flatMap(t=>windows(t,radius));if(!boxes.length)continue;const data=await overpass(query(boxes));stats.requests++;stats.elementsReceived+=data.elements?.length||0;for(const t of pending){const rows=(data.elements||[]).map(e=>makeAddress(e,t)).filter(Boolean);const map=new Map();for(const a of rows){const k=[country,a.postcode||a.city,a.street,a.houseNumber].map(norm).join('|');if(!map.has(k)||map.get(k).qualityScore<a.qualityScore)map.set(k,a)}all.set(t.id,[...(all.get(t.id)||[]),...map.values()].sort((a,b)=>b.qualityScore-a.qualityScore||a.id.localeCompare(b.id)));}await new Promise(r=>setTimeout(r,500));}stats.countries++;for(const t of ts){const cap=manifest.candidateProfiles[t.scope].outputCap;const groups=new Map();for(const a of (all.get(t.id)||[])){const k=[a.region,a.city,a.postcode||'*'].map(norm).join('|');const v=groups.get(k)||[];if(v.length<3)v.push(a);groups.set(k,v)}const addresses=[...groups.values()].flat().slice(0,cap);const regions=[...new Map(addresses.map(a=>[a.region,{name:a.region,cities:[]}])).values()];for(const r of regions){const cs=[...new Map(addresses.filter(a=>a.region===r.name).map(a=>[a.city,{name:a.city,postcodes:[]}])).values()];for(const c of cs)c.postcodes=[...new Map(addresses.filter(a=>a.region===r.name&&a.city===c.name).map(a=>[a.postcode||'',{postcode:a.postcode||'',addresses:a?addresses.filter(x=>x.region===r.name&&x.city===c.name&&(x.postcode||'')===(a.postcode||'')):[]}])).values()];r.cities=cs}const payload={schemaVersion:1,generatedAt:new Date().toISOString(),country,target:{id:t.id,label:t.label,labelZh:t.labelZh,category:t.category,scope:t.scope,bounds:t.bounds,note:t.note||'',...(t.tax?{tax:t.tax}:{})},stats:{addresses:addresses.length,regions:regions.length,cities:regions.reduce((n,r)=>n+r.cities.length,0),postcodes:regions.reduce((n,r)=>n+r.cities.reduce((m,c)=>m+c.postcodes.length,0),0),maxAddressesPerPostcode:3,maxAddressesPerTarget:cap,probeRequests:stats.requests,elementsReceived:stats.elementsReceived,accepted:addresses.length,rejected:0,pass:true},regions};await mkdir(dirname(resolve(out,t.file)),{recursive:true});await writeFile(resolve(out,t.file),JSON.stringify(payload)+'\n');if(!addresses.length)stats.emptyTargets++;stats.acceptedAddresses+=addresses.length;}}catch(e){stats.failedCountries.push({country,error:String(e)});}}stats.finishedAt=new Date().toISOString();stats.elapsedMs=Date.now()-started;await mkdir(dirname(metricsPath),{recursive:true});await writeFile(metricsPath,JSON.stringify(stats,null,2)+'\n');if(stats.failedCountries.length)throw new AggregateError(stats.failedCountries.map(x=>new Error(`${x.country}: ${x.error}`)),'Lite native refresh failed');
