import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import process from 'node:process';

export const ENDPOINTS = ['https://overpass.private.coffee/api/interpreter', 'https://maps.mail.ru/osm/tools/overpass/api/interpreter', 'https://overpass-api.de/api/interpreter'];
export const USER_AGENT = 'Address-Lite/1.0 (+https://github.com/Piggy-Cat-bit-shadow/address)';
export const REFERER = 'https://github.com/Piggy-Cat-bit-shadow/address';
export const MAX_HTTP_REQUESTS = 90;
const root = resolve(new URL('../..', import.meta.url).pathname);
const residential = new Set(['apartments', 'bungalow', 'cabin', 'detached', 'dormitory', 'ger', 'house', 'residential', 'semidetached_house', 'semi', 'terrace']);
const blocked = ['amenity', 'shop', 'office', 'tourism', 'industrial', 'craft', 'healthcare', 'military'];
const radii = { micro: [.010, .010], city: [.020, .015], region: [.035, .025] };
const retryable = new Set([408, 429, 500, 502, 503, 504]);
const norm = value => String(value || '').normalize('NFKD').replace(/\p{M}+/gu, '').trim().toLocaleLowerCase('und');
const sleep = ms => new Promise(resolveDelay => setTimeout(resolveDelay, ms));
const inside = (lon, lat, bounds) => lon >= bounds[0] && lon <= bounds[2] && lat >= bounds[1] && lat <= bounds[3];

export const probeWindows = (target, pass = 1) => {
  const [dx, dy] = radii[target.scope] || radii.city; const factor = pass === 1 ? 1 : 2;
  return (target.seeds || []).slice(0, 4).map(([lon, lat]) => { const box = [Math.max(target.bounds[0], lon - dx * factor), Math.max(target.bounds[1], lat - dy * factor), Math.min(target.bounds[2], lon + dx * factor), Math.min(target.bounds[3], lat + dy * factor)]; return box[0] < box[2] && box[1] < box[3] ? box : null; }).filter(Boolean);
};

export const overpassQuery = boxes => `[out:json][timeout:30];(${boxes.flatMap(([west, south, east, north]) => [
  `nwr[building~"^(apartments|bungalow|cabin|detached|dormitory|ger|house|residential|semidetached_house|semi|terrace)$"]["addr:housenumber"]["addr:street"](${south},${west},${north},${east});`,
  `nwr[building~"^(apartments|bungalow|cabin|detached|dormitory|ger|house|residential|semidetached_house|semi|terrace)$"]["addr:housenumber"]["addr:place"](${south},${west},${north},${east});`,
]).join('')});out center tags;`;

export const filterAddresses = (elements, target) => elements.map(element => {
  const tags = element.tags || {}; const point = element.center || (Number.isFinite(element.lat) && Number.isFinite(element.lon) ? { lat: element.lat, lon: element.lon } : null); const rawRegion = tags['addr:state'] || tags['addr:province'] || tags['addr:region'];
  if (!point || !residential.has(tags.building) || !tags['addr:housenumber'] || !(tags['addr:street'] || tags['addr:place']) || !inside(point.lon, point.lat, target.bounds)) return null;
  if (blocked.some(key => tags[key] && !['', 'no', 'none'].includes(norm(tags[key])))) return null;
  if (target.regionAliases?.length && rawRegion && !target.regionAliases.some(alias => norm(alias) === norm(rawRegion))) return null;
  const street = tags['addr:street'] || tags['addr:place']; const city = tags['addr:city'] || tags['addr:town'] || tags['addr:municipality'] || tags.municipality || tags['addr:village'] || tags['addr:suburb'] || target.label; const region = rawRegion || target.label; const postcode = tags['addr:postcode'] || ''; const id = `osm:${element.type}:${element.id}`;
  return { id, region, regionCode: tags['addr:state_code'] || '', city, locality: city, postalLocality: city, district: tags['addr:district'] || tags['addr:county'] || tags['addr:suburb'] || '', postcode, street, houseNumber: tags['addr:housenumber'], buildingName: tags.name || '', unit: tags['addr:unit'] || tags['addr:flats'] || '', latitude: point.lat, longitude: point.lon, propertyType: tags.building === 'apartments' ? 'apartment' : 'residential', residentialEvidence: true, qualityScore: 100 + (postcode ? 20 : 0) + (city ? 10 : 0) + (rawRegion ? 5 : 0) + (tags.building === 'apartments' ? 2 : 0), formattedAddress: [tags['addr:housenumber'], street, city, region, postcode, tags['addr:country']].filter(Boolean).join(', '), formattedAddressEn: '', formattedAddressZh: '', source: { name: 'OpenStreetMap', url: `https://www.openstreetmap.org/${element.type}/${element.id}`, license: 'ODbL 1.0', licenseUrl: 'https://opendatacommons.org/licenses/odbl/1-0/', attribution: '© OpenStreetMap contributors', attributionUrl: 'https://www.openstreetmap.org/copyright', datasetVersion: `overpass:${new Date().toISOString().slice(0, 10)}`, sourceRecordId: `${element.type}/${element.id}` } };
}).filter(Boolean);

export const isRetryableError = error => retryable.has(error?.status) || retryable.has(Number(String(error?.message || '').match(/HTTP (\d+)/)?.[1]) || 0) || ['AbortError', 'TimeoutError'].includes(error?.name) || String(error?.message || '').includes('fetch failed');
export const endpointName = endpoint => new URL(endpoint).hostname.replace(/^www\./, '');
const headers = { 'User-Agent': USER_AGENT, Referer: REFERER, Accept: 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' };

export const createOverpassClient = ({ fetchImpl = globalThis.fetch, log = () => {}, maxRequests = MAX_HTTP_REQUESTS } = {}) => {
  const names = Object.fromEntries(ENDPOINTS.map(endpoint => [endpointName(endpoint), 0])); const metrics = { requests: 0, retries: 0, failovers: 0, fallbackRequests: 0, endpointRequests: { ...names }, endpointFailures: { ...names }, endpoint429: { ...names }, healthyEndpoints: [], requestBudgetUsed: 0, elementsReceived: 0 }; const cooldownUntil = new Map();
  const fail = (endpoint, error) => { metrics.endpointFailures[endpointName(endpoint)] += 1; if (error?.status === 429) metrics.endpoint429[endpointName(endpoint)] += 1; };
  const healthProbe = async () => { const query = '[out:json][timeout:5];node(0,0,0.0001,0.0001);out 1;'; for (const endpoint of ENDPOINTS) { if (metrics.requestBudgetUsed >= maxRequests) throw new Error('overpass_request_budget_exhausted'); metrics.requests += 1; metrics.requestBudgetUsed += 1; metrics.endpointRequests[endpointName(endpoint)] += 1; try { const response = await fetchImpl(endpoint, { method: 'POST', body: new URLSearchParams({ data: query }), headers, signal: AbortSignal.timeout(10_000) }); if (!response.ok) throw Object.assign(new Error(`Overpass HTTP ${response.status}`), { status: response.status }); const data = await response.json(); if (!Array.isArray(data.elements)) throw new Error('Overpass invalid JSON'); metrics.healthyEndpoints.push(endpoint); } catch (error) { fail(endpoint, error); } } log(`[OSM] endpoints healthy=${metrics.healthyEndpoints.length}/${ENDPOINTS.length}`); if (!metrics.healthyEndpoints.length) throw new Error('overpass_no_healthy_endpoint'); };
  const request = async (query, preferredIndex = 0) => { const healthy = metrics.healthyEndpoints.filter(endpoint => (cooldownUntil.get(endpoint) || 0) <= Date.now()); if (!healthy.length) throw new Error('overpass_no_available_endpoint'); let last; for (let i = 0; i < healthy.length; i += 1) { const endpoint = healthy[(preferredIndex + i) % healthy.length]; if (metrics.requestBudgetUsed >= maxRequests) throw new Error('overpass_request_budget_exhausted'); metrics.requests += 1; metrics.requestBudgetUsed += 1; metrics.endpointRequests[endpointName(endpoint)] += 1; try { const response = await fetchImpl(endpoint, { method: 'POST', body: new URLSearchParams({ data: query }), headers, signal: AbortSignal.timeout(35_000) }); if (response.ok) { const data = await response.json(); metrics.elementsReceived += data.elements?.length || 0; return data.elements || []; } const error = Object.assign(new Error(`Overpass HTTP ${response.status}`), { status: response.status }); if (!retryable.has(response.status)) throw error; last = error; fail(endpoint, error); if (response.status === 429) { const retryAfter = Number(response.headers.get('retry-after')); cooldownUntil.set(endpoint, Date.now() + (Number.isFinite(retryAfter) && retryAfter >= 0 ? retryAfter * 1000 : 30_000)); } metrics.failovers += 1; metrics.retries += 1; metrics.fallbackRequests += 1; log(`[OSM] failover endpoint=${endpointName(endpoint)} status=${response.status}`); } catch (error) { last = error; if (!isRetryableError(error)) throw error; fail(endpoint, error); metrics.failovers += 1; metrics.retries += 1; metrics.fallbackRequests += 1; log(`[OSM] failover endpoint=${endpointName(endpoint)} status=network`); } } throw last; };
  return { metrics, healthProbe, request };
};

const addressCount = data => Number(data?.stats?.addresses ?? data?.regions?.flatMap(region => region.cities.flatMap(city => city.postcodes.flatMap(postcode => postcode.addresses))).length ?? 0);
const validShard = data => data && data.schemaVersion === 1 && data.stats && Array.isArray(data.regions);
const hierarchy = (target, addresses, manifest) => { const groups = new Map(); for (const address of addresses) { const key = [address.region, address.city, address.postcode || '*'].map(norm).join('|'); const bucket = groups.get(key) || []; if (bucket.length < 3) bucket.push(address); groups.set(key, bucket); } const selected = [...groups.values()].flat().sort((a, b) => b.qualityScore - a.qualityScore || a.id.localeCompare(b.id)).slice(0, manifest.candidateProfiles[target.scope].outputCap); const regions = [...new Map(selected.map(address => [address.region, { name: address.region, cities: [] }])).values()]; for (const region of regions) { const cities = [...new Map(selected.filter(address => address.region === region.name).map(address => [address.city, { name: address.city, postcodes: [] }])).values()]; for (const city of cities) city.postcodes = [...new Map(selected.filter(address => address.region === region.name && address.city === city.name).map(address => [address.postcode || '', { postcode: address.postcode || '', addresses: selected.filter(item => item.region === region.name && item.city === city.name && (item.postcode || '') === (address.postcode || '')) }])).values()]; region.cities = cities; } return { selected, regions }; };
const shard = (target, selected, regions, manifest, country) => ({ schemaVersion: 1, generatedAt: new Date().toISOString(), country, target: { id: target.id, label: target.label, labelZh: target.labelZh, category: target.category, scope: target.scope, bounds: target.bounds, note: target.note || '', ...(target.tax ? { tax: target.tax } : {}) }, stats: { addresses: selected.length, regions: regions.length, cities: regions.reduce((sum, region) => sum + region.cities.length, 0), postcodes: regions.reduce((sum, region) => sum + region.cities.reduce((sum2, city) => sum2 + city.postcodes.length, 0), 0), maxAddressesPerPostcode: 3, maxAddressesPerTarget: manifest.candidateProfiles[target.scope].outputCap, probeRequests: 0, accepted: selected.length, rejected: 0, pass: true }, regions });

export const runNativeRefresh = async ({ manifest, seeds, out, metricsFile, fetchImpl, fallbackData, log = console.log } = {}) => {
  const client = createOverpassClient({ fetchImpl, log }); await mkdir(out, { recursive: true }); const tracked = join(root, 'data/lite-baseline'); const baselineRoot = fallbackData || tracked; const baselineSource = fallbackData ? 'snapshot' : 'tracked-baseline'; const startedAt = new Date().toISOString(); const baseline = new Map(); const missing = [];
  for (const target of manifest.targets) { let data; let sourcePath; for (const candidate of [join(baselineRoot, target.file), fallbackData ? join(tracked, target.file) : null].filter(Boolean)) { try { data = JSON.parse(await readFile(candidate, 'utf8')); if (validShard(data)) { sourcePath = candidate; break; } data = null; } catch {} } if (data) { baseline.set(target.id, data); await mkdir(dirname(join(out, target.file)), { recursive: true }); try { await copyFile(sourcePath, join(out, target.file)); } catch { await writeFile(join(out, target.file), `${JSON.stringify(data)}\n`); } } else missing.push(target.id); }
  log(`[OSM] baseline source=${baselineSource} targets=${baseline.size}`); await client.healthProbe(); const countries = [...new Set(manifest.targets.map(target => target.country))]; const found = new Map(manifest.targets.map(target => [target.id, []])); const errors = new Map(); let batchCount = 0; let batchSplits = 0;
  const runBatch = async (country, batch, pass, preferredIndex) => { batchCount += 1; const endpoint = client.metrics.healthyEndpoints[preferredIndex % client.metrics.healthyEndpoints.length]; log(`[OSM] pass=${pass} country=${country} batch=${batchCount} targets=${batch.length} endpoint=${endpointName(endpoint)}`); try { const elements = await client.request(overpassQuery(batch.flatMap(target => probeWindows(target, pass))), preferredIndex); for (const target of batch) { const existing = new Map(found.get(target.id).map(address => [address.id, address])); for (const address of filterAddresses(elements, target)) existing.set(address.id, address); found.set(target.id, [...existing.values()]); } log(`[OSM] success country=${country} batch=${batchCount} selected=${batch.map(target => found.get(target.id).length).join(',')}`); } catch (error) { if (batch.length > 1 && isRetryableError(error)) { const mid = Math.ceil(batch.length / 2); batchSplits += 1; log(`[OSM] split country=${country} targets=${batch.length} -> ${mid}+${batch.length - mid}`); await runBatch(country, batch.slice(0, mid), pass, preferredIndex); await runBatch(country, batch.slice(mid), pass, preferredIndex + 1); } else { for (const target of batch) errors.set(target.id, error); if (String(error.message).includes('request_budget_exhausted')) log('[OSM] request budget exhausted; switching remaining targets to baseline'); } } };
  for (const country of countries) { const targets = manifest.targets.filter(target => target.country === country).map(target => ({ ...target, seeds: seeds.targets[target.id] || [] })); for (const pass of [1, 2]) { const pending = targets.filter(target => found.get(target.id).length < 3 && !errors.has(target.id)); for (let i = 0; i < pending.length; i += 4) { if (client.metrics.requestBudgetUsed >= MAX_HTTP_REQUESTS) { for (const target of pending.slice(i)) errors.set(target.id, new Error('overpass_request_budget_exhausted')); break; } await runBatch(country, pending.slice(i, i + 4), pass, i / 4); await sleep(750); } } }
  let refreshedTargets = 0; let reusedTargets = 0; let reusedNetworkTargets = 0; let reusedEmptyTargets = 0; let reusedRegressionTargets = 0; let emptyTargets = 0; const fatalTargets = [];
  for (const target of manifest.targets) { const fresh = hierarchy(target, found.get(target.id), manifest); const old = baseline.get(target.id); const oldCount = addressCount(old); const freshCount = fresh.selected.length; const error = errors.get(target.id); let state; if (freshCount > 0 && (oldCount === 0 || freshCount >= oldCount)) { state = 'refreshed'; refreshedTargets += 1; await mkdir(dirname(join(out, target.file)), { recursive: true }); await writeFile(join(out, target.file), `${JSON.stringify(shard(target, fresh.selected, fresh.regions, manifest, target.country))}\n`); } else if (old) { state = error ? 'reused-network' : freshCount === 0 ? 'reused-empty' : 'reused-regression'; reusedTargets += 1; if (state === 'reused-network') reusedNetworkTargets += 1; if (state === 'reused-empty') reusedEmptyTargets += 1; if (state === 'reused-regression') reusedRegressionTargets += 1; } else if (error) { state = 'fatal'; fatalTargets.push(target.id); } else { state = 'empty'; emptyTargets += 1; } log(`[OSM] country=${target.country} target=${target.id} ${state} old=${oldCount} new=${freshCount}`); }
  const metrics = { startedAt, finishedAt: new Date().toISOString(), elapsedMs: Date.now() - Date.parse(startedAt), countries: countries.length, targets: manifest.targets.length, baselineSource, baselineSnapshotId: '', ...client.metrics, batchCount, batchSplits, refreshedTargets, reusedTargets, reusedNetworkTargets, reusedEmptyTargets, reusedRegressionTargets, emptyTargets, fatalTargets, failedTargets: fatalTargets }; await mkdir(dirname(metricsFile), { recursive: true }); await writeFile(metricsFile, `${JSON.stringify(metrics, null, 2)}\n`); log(`[OSM] complete refreshed=${refreshedTargets} reused=${reusedTargets} empty=${emptyTargets} fatal=${fatalTargets.length}`); if (fatalTargets.length || baseline.size !== manifest.targets.length) throw new Error(`Lite native refresh fatal targets: ${fatalTargets.join(',') || missing.join(',')}`); return metrics;
};

if (process.argv[1] === new URL(import.meta.url).pathname) { const arg = (name, fallback = '') => { const index = process.argv.indexOf(name); return index < 0 ? fallback : process.argv[index + 1]; }; const manifest = JSON.parse(await readFile(resolve(root, 'config/lite-targets.json'), 'utf8')); const seeds = JSON.parse(await readFile(resolve(root, 'config/lite-seeds.json'), 'utf8')); const out = resolve(arg('--out', resolve(root, '.lite-output'))); const metricsFile = resolve(arg('--metrics', resolve(out, 'metrics/native.json'))); await runNativeRefresh({ manifest, seeds, out, metricsFile, fallbackData: arg('--fallback-data') || undefined }); }
