import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import process from 'node:process';

export const ENDPOINTS = ['https://overpass.private.coffee/api/interpreter','https://maps.mail.ru/osm/tools/overpass/api/interpreter','https://overpass-api.de/api/interpreter'];
export const USER_AGENT = 'Address-Lite/1.0 (+https://github.com/Piggy-Cat-bit-shadow/address)';
export const REFERER = 'https://github.com/Piggy-Cat-bit-shadow/address';
export const MAX_HTTP_REQUESTS = 90;
const root = resolve(new URL('../..', import.meta.url).pathname);
const residential = new Set(['apartments','bungalow','cabin','detached','dormitory','ger','house','residential','semidetached_house','semi','terrace']);
const blocked = ['amenity','shop','office','tourism','industrial','craft','healthcare','military'];
const norm = value => String(value || '').normalize('NFKD').replace(/\p{M}+/gu, '').trim().toLocaleLowerCase('und');
const inside = (lon, lat, b) => lon >= b[0] && lon <= b[2] && lat >= b[1] && lat <= b[3];
const radii = { micro: [.010,.010], city: [.020,.015], region: [.035,.025] };
const retryable = new Set([408,429,500,502,503,504]);
const sleep = ms => new Promise(resolveDelay => setTimeout(resolveDelay, ms));

export const probeWindows = (target, pass = 1) => {
  const [dx, dy] = radii[target.scope] || radii.city; const factor = pass === 1 ? 1 : 2;
  return (target.seeds || []).slice(0, 4).map(([lon, lat]) => { const box = [Math.max(target.bounds[0], lon - dx * factor), Math.max(target.bounds[1], lat - dy * factor), Math.min(target.bounds[2], lon + dx * factor), Math.min(target.bounds[3], lat + dy * factor)]; return box[0] < box[2] && box[1] < box[3] ? box : null; }).filter(Boolean);
};

export const overpassQuery = boxes => `[out:json][timeout:30];(${boxes.flatMap(([west,south,east,north]) => [
  `nwr[building~"^(apartments|bungalow|cabin|detached|dormitory|ger|house|residential|semidetached_house|semi|terrace)$"]["addr:housenumber"]["addr:street"](${south},${west},${north},${east});`,
  `nwr[building~"^(apartments|bungalow|cabin|detached|dormitory|ger|house|residential|semidetached_house|semi|terrace)$"]["addr:housenumber"]["addr:place"](${south},${west},${north},${east});`,
]).join('')});out center tags;`;

export const filterAddresses = (elements, target) => elements.map(element => {
  const tags = element.tags || {}; const point = element.center || (Number.isFinite(element.lat) && Number.isFinite(element.lon) ? { lat: element.lat, lon: element.lon } : null); const rawRegion = tags['addr:state'] || tags['addr:province'] || tags['addr:region'];
  if (!point || !residential.has(tags.building) || !tags['addr:housenumber'] || !(tags['addr:street'] || tags['addr:place']) || !inside(point.lon, point.lat, target.bounds)) return null;
  if (blocked.some(key => tags[key] && !['','no','none'].includes(norm(tags[key])))) return null;
  if (target.regionAliases?.length && rawRegion && !target.regionAliases.some(alias => norm(alias) === norm(rawRegion))) return null;
  const street = tags['addr:street'] || tags['addr:place']; const city = tags['addr:city'] || tags['addr:town'] || tags['addr:municipality'] || tags.municipality || tags['addr:village'] || tags['addr:suburb'] || target.label; const region = rawRegion || target.label; const postcode = tags['addr:postcode'] || ''; const id = `osm:${element.type}:${element.id}`;
  return { id, region, regionCode: tags['addr:state_code'] || '', city, locality: city, postalLocality: city, district: tags['addr:district'] || tags['addr:county'] || tags['addr:suburb'] || '', postcode, street, houseNumber: tags['addr:housenumber'], buildingName: tags.name || '', unit: tags['addr:unit'] || tags['addr:flats'] || '', latitude: point.lat, longitude: point.lon, propertyType: tags.building === 'apartments' ? 'apartment' : 'residential', residentialEvidence: true, qualityScore: 100 + (postcode ? 20 : 0) + (city ? 10 : 0) + (rawRegion ? 5 : 0) + (tags.building === 'apartments' ? 2 : 0), formattedAddress: [tags['addr:housenumber'], street, city, region, postcode, tags['addr:country']].filter(Boolean).join(', '), formattedAddressEn: '', formattedAddressZh: '', source: { name: 'OpenStreetMap', url: `https://www.openstreetmap.org/${element.type}/${element.id}`, license: 'ODbL 1.0', licenseUrl: 'https://opendatacommons.org/licenses/odbl/1-0/', attribution: '© OpenStreetMap contributors', attributionUrl: 'https://www.openstreetmap.org/copyright', datasetVersion: `overpass:${new Date().toISOString().slice(0,10)}`, sourceRecordId: `${element.type}/${element.id}` } };
}).filter(Boolean);

export const isRetryableError = error => retryable.has(error?.status) || retryable.has(Number(String(error?.message || '').match(/HTTP (\d+)/)?.[1]) || 0) || ['AbortError','TimeoutError'].includes(error?.name) || String(error?.message || '').includes('fetch failed');
export const endpointName = endpoint => new URL(endpoint).hostname.replace(/^www\./, '');
const headers = { 'User-Agent': USER_AGENT, Referer: REFERER, Accept: 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' };

export const createOverpassClient = ({ fetchImpl = globalThis.fetch, log = () => {}, maxRequests = MAX_HTTP_REQUESTS } = {}) => {
  const names = Object.fromEntries(ENDPOINTS.map(endpoint => [endpointName(endpoint), 0])); const metrics = { requests: 0, retries: 0, failovers: 0, fallbackRequests: 0, endpointRequests: { ...names }, endpointFailures: { ...names }, endpoint429: { ...names }, batchCount: 0, batchSplits: 0, requestBudgetUsed: 0, healthyEndpoints: [], elementsReceived: 0 }; const cooldownUntil = new Map();
  const count = (endpoint, field) => { metrics[field][endpointName(endpoint)] += 1; };
  const healthProbe = async () => { const query = '[out:json][timeout:5];node(0,0,0.0001,0.0001);out 1;'; for (const endpoint of ENDPOINTS) { if (metrics.requestBudgetUsed >= maxRequests) throw new Error('overpass_request_budget_exhausted'); metrics.requests += 1; metrics.requestBudgetUsed += 1; metrics.endpointRequests[endpointName(endpoint)] += 1; try { const response = await fetchImpl(endpoint, { method: 'POST', body: new URLSearchParams({ data: query }), headers, signal: AbortSignal.timeout(10_000) }); if (!response.ok) throw Object.assign(new Error(`Overpass HTTP ${response.status}`), { status: response.status }); const data = await response.json(); if (!Array.isArray(data.elements)) throw new Error('Overpass invalid JSON'); metrics.healthyEndpoints.push(endpoint); } catch (error) { count(endpoint, 'endpointFailures'); if (error?.status === 429) count(endpoint, 'endpoint429'); } } log(`[OSM] endpoints healthy=${metrics.healthyEndpoints.length}/${ENDPOINTS.length}`); if (!metrics.healthyEndpoints.length) throw new Error('overpass_no_healthy_endpoint'); };
  const request = async (query, preferredIndex = 0) => { const healthy = metrics.healthyEndpoints.filter(endpoint => (cooldownUntil.get(endpoint) || 0) <= Date.now()); if (!healthy.length) throw new Error('overpass_no_available_endpoint'); let last; for (let i = 0; i < healthy.length; i += 1) { const endpoint = healthy[(preferredIndex + i) % healthy.length]; if (metrics.requestBudgetUsed >= maxRequests) throw new Error('overpass_request_budget_exhausted'); metrics.requests += 1; metrics.requestBudgetUsed += 1; metrics.endpointRequests[endpointName(endpoint)] += 1; try { const response = await fetchImpl(endpoint, { method: 'POST', body: new URLSearchParams({ data: query }), headers, signal: AbortSignal.timeout(35_000) }); if (response.ok) { const data = await response.json(); metrics.elementsReceived += data.elements?.length || 0; return data.elements || []; } const error = Object.assign(new Error(`Overpass HTTP ${response.status}`), { status: response.status }); if (!retryable.has(response.status)) throw error; last = error; count(endpoint, 'endpointFailures'); if (response.status === 429) { count(endpoint, 'endpoint429'); const retryAfter = Number(response.headers.get('retry-after')); cooldownUntil.set(endpoint, Date.now() + (Number.isFinite(retryAfter) && retryAfter >= 0 ? retryAfter * 1000 : 30_000)); } metrics.failovers += 1; metrics.retries += 1; metrics.fallbackRequests += 1; log(`[OSM] failover endpoint=${endpointName(endpoint)} status=${response.status}`); } catch (error) { last = error; if (!isRetryableError(error)) throw error; count(endpoint, 'endpointFailures'); metrics.failovers += 1; metrics.retries += 1; metrics.fallbackRequests += 1; log(`[OSM] failover endpoint=${endpointName(endpoint)} status=network`); } } throw last; };
  return { metrics, healthProbe, request };
};

const hierarchy = (target, addresses, manifest) => { const groups = new Map(); for (const address of addresses) { const key = [address.region, address.city, address.postcode || '*'].map(norm).join('|'); const bucket = groups.get(key) || []; if (bucket.length < 3) bucket.push(address); groups.set(key, bucket); } const selected = [...groups.values()].flat().sort((a,b) => b.qualityScore - a.qualityScore || a.id.localeCompare(b.id)).slice(0, manifest.candidateProfiles[target.scope].outputCap); const regions = [...new Map(selected.map(a => [a.region, { name: a.region, cities: [] }])).values()]; for (const region of regions) { const cities = [...new Map(selected.filter(a => a.region === region.name).map(a => [a.city, { name: a.city, postcodes: [] }])).values()]; for (const city of cities) city.postcodes = [...new Map(selected.filter(a => a.region === region.name && a.city === city.name).map(a => [a.postcode || '', { postcode: a.postcode || '', addresses: selected.filter(x => x.region === region.name && x.city === city.name && (x.postcode || '') === (a.postcode || '')) }])).values()]; region.cities = cities; } return { selected, regions }; };

export const runNativeRefresh = async ({ manifest, seeds, out, metricsFile, fetchImpl, log = console.log } = {}) => { const client = createOverpassClient({ fetchImpl, log }); await mkdir(out, { recursive: true }); const startedAt = new Date().toISOString(); await client.healthProbe(); const failedCountries = []; const failedTargets = []; let emptyTargets = 0; let acceptedAddresses = 0; let batchCount = 0; let batchSplits = 0; const countries = [...new Set(manifest.targets.map(target => target.country))];
  for (const country of countries) { const targets = manifest.targets.filter(target => target.country === country).map(target => ({ ...target, seeds: seeds.targets[target.id] || [] })); const found = new Map(targets.map(target => [target.id, []])); const merge = (target, elements) => { const map = new Map(found.get(target.id).map(address => [[country, address.postcode || address.city, address.street, address.houseNumber].map(norm).join('|'), address])); for (const address of filterAddresses(elements, target)) { const key = [country, address.postcode || address.city, address.street, address.houseNumber].map(norm).join('|'); if (!map.has(key) || map.get(key).qualityScore < address.qualityScore) map.set(key, address); } found.set(target.id, [...map.values()]); };
    const runBatch = async (batch, pass, preferredIndex) => { batchCount += 1; client.metrics.batchCount = batchCount; const endpoint = client.metrics.healthyEndpoints[preferredIndex % client.metrics.healthyEndpoints.length]; log(`[OSM] pass=${pass} country=${country} batch=${batchCount} targets=${batch.length} endpoint=${endpointName(endpoint)}`); try { const elements = await client.request(overpassQuery(batch.flatMap(target => probeWindows(target, pass))), preferredIndex); batch.forEach(target => merge(target, elements)); log(`[OSM] success country=${country} batch=${batchCount} selected=${batch.map(target => found.get(target.id).length).join(',')}`); } catch (error) { if (batch.length > 1 && isRetryableError(error)) { const mid = Math.ceil(batch.length / 2); batchSplits += 1; client.metrics.batchSplits = batchSplits; log(`[OSM] split country=${country} targets=${batch.length} -> ${mid}+${batch.length-mid}`); await runBatch(batch.slice(0, mid), pass, preferredIndex); await runBatch(batch.slice(mid), pass, preferredIndex + 1); } else throw error; } };
    try { for (const pass of [1, 2]) { const pending = targets.filter(target => found.get(target.id).length < 3); for (let i = 0; i < pending.length; i += 4) { await runBatch(pending.slice(i, i + 4), pass, i / 4); await sleep(750); } } for (const target of targets) { const { selected, regions } = hierarchy(target, found.get(target.id), manifest); if (!selected.length) emptyTargets += 1; acceptedAddresses += selected.length; const cap = manifest.candidateProfiles[target.scope].outputCap; const result = { schemaVersion: 1, generatedAt: new Date().toISOString(), country, target: { id: target.id, label: target.label, labelZh: target.labelZh, category: target.category, scope: target.scope, bounds: target.bounds, note: target.note || '', ...(target.tax ? { tax: target.tax } : {}) }, stats: { addresses: selected.length, regions: regions.length, cities: regions.reduce((sum, region) => sum + region.cities.length, 0), postcodes: regions.reduce((sum, region) => sum + region.cities.reduce((sum2, city) => sum2 + city.postcodes.length, 0), 0), maxAddressesPerPostcode: 3, maxAddressesPerTarget: cap, probeRequests: 0, elementsReceived: client.metrics.elementsReceived, accepted: selected.length, rejected: 0, pass: true }, regions }; await mkdir(dirname(resolve(out, target.file)), { recursive: true }); await writeFile(resolve(out, target.file), `${JSON.stringify(result)}\n`); } log(`[OSM] country=${country} complete`); } catch (error) { failedCountries.push({ country, error: String(error) }); targets.forEach(target => { if (!found.get(target.id).length) failedTargets.push(target.id); }); } }
  const metrics = { startedAt, finishedAt: new Date().toISOString(), elapsedMs: Date.now() - Date.parse(startedAt), countries: countries.length, targets: manifest.targets.length, ...client.metrics, batchCount, batchSplits, acceptedAddresses, emptyTargets, failedTargets, failedCountries }; await mkdir(dirname(metricsFile), { recursive: true }); await writeFile(metricsFile, `${JSON.stringify(metrics, null, 2)}\n`); if (failedCountries.length) throw new AggregateError(failedCountries.map(item => new Error(`${item.country}: ${item.error}`)), 'Lite native refresh failed'); return metrics;
};

if (process.argv[1] === new URL(import.meta.url).pathname) { const arg = (name, fallback = '') => { const i = process.argv.indexOf(name); return i < 0 ? fallback : process.argv[i + 1]; }; const manifest = JSON.parse(await readFile(resolve(root, 'config/lite-targets.json'), 'utf8')); const seeds = JSON.parse(await readFile(resolve(root, 'config/lite-seeds.json'), 'utf8')); const out = resolve(arg('--out', resolve(root, '.lite-output'))); const metricsFile = resolve(arg('--metrics', resolve(out, 'metrics/native.json'))); await runNativeRefresh({ manifest, seeds, out, metricsFile }); }
